packages:
  aur:
    android-studio:
    android-tools:
    ansible:
    archive-mounter:
    aria2:
    asciinema:
    aurvote:
    bash-pipes:
    catimg:
    cava:
    cawbird:
    ccze:
    chkservice:
    cmake:
    cmatrix:
    conky:
    cowsay:
    ctop:
    curl:
    dconf-editor:
    dnsmasq:
    docker:
    ebtables:
    emojify:
    exa:
    feedreader:
    flameshot:
    flatpak:
    fortune-mod:
    fswebcam:
    fzy:
    gconf-editor:
    gitflow-avh:
    gnome-session-properties:
    gotop-bin:
    hexchat:
    htop:
    httpie:
    imagemagick:
    iotop:
    kodi:
    kubectl-bin:
    kubernetes-helm-bin:
    libvirt:
    lolcat:
    meld:
    mpd:
    mtr:
    navi:
    ncmpcpp:
    neofetch:
    neovim:
    nerd-fonts-complete:
    nethogs:
    nnn:
    pamac-aur:
    pcsc-tools:
    peek:
    pigz:
    pkgconf:
    plata-theme:
    ponysay:
    powershell-bin:
    powertop:
    python-pyfiglet:
    python-pywinrm:
    python-whichcraft:
    qemu:
    qt5-styleplugins:
    qt5ct:
    reflector:
    retroarch:
    rofi:
    rsync:
    ruby-bundler:
    ruby-libvirt:
    ruby-rake:
    ruby-rdoc:
    ruby:
    scrot:
    seahorse:
    shellcheck:
    spotify-dev:
    sshfs:
    steam-fonts:
    sysprof:
    telegram-desktop:
    terminus-font:
    terraform:
    tig:
    tilix:
    tmate:
    tmux-xpanes:
    tmux:
    tree:
    vagrant:
    vim:
    virt-manager:
    visual-studio-code-insiders:
    wpscan:
    xclip:
    yay:
    youtube-viewer:
    zsh:

# The VS Code build (either 'stable' or 'insiders') https://code.visualstudio.com/insiders/
visual_studio_code_extensions_build: insiders
users:
  - username: npanic
    # Extensions to be installed if not already present
    visual_studio_code_extensions:
      - 343max.android-emulator-launcher
      - adelphes.android-dev-ext
      - alefragnani.Bookmarks
      - alefragnani.project-manager
      - arahulc91.androidify
      - azemoh.one-monokai
      - balazs4.gitlab-pipeline-monitor
      - bbenoist.vagrant
      - blueneogeo.flutter-view-vscode
      - brendandburns.vs-kubernetes
      - brittanychiang.halcyon-vscode
      - carolynvs.dep
      - casualjim.gotemplate
      - codeflows.vaulty
      - codezombiech.gitignore
      - CoenraadS.bracket-pair-colorizer
      - coolbear.systemd-unit-file
      - cssho.vscode-svgviewer
      - Dart-Code.dart-code
      - Dart-Code.flutter
      - DavidAnson.vscode-markdownlint
      - dbaeumer.vscode-eslint
      - dhoeric.ansible-vault
      - donjayamanne.githistory
      - DryWolf.dark-plus-plus-theme
      - dunstontc.vscode-docker-syntax
      - eamodio.gitlens
      - EditorConfig.EditorConfig
      - eg2.vscode-npm-script
      - emmanuelbeziat.vscode-great-icons
      - Equinusocio.vsc-material-theme
      - erd0s.terraform-autocomplete
      - eserozvataf.one-dark-pro-monokai-darker
      - fatihacet.gitlab-workflow
      - felipecaputo.git-project-manager
      - formulahendry.docker-explorer
      - gmlewis-vscode.flutter-stylizer
      - haaaad.ansible
      - henriiik.docker-linter
      - howardzuo.vscode-git-tags
      - ilevine.kubesquash
      - ilevine.squash
      - ipedrazas.kubernetes-snippets
      - jaredkent.vsthemegenerator
      - jasonn-porch.gitlab-mr
      - jeroen-meijer.pubspec-assist
      - johnpapa.vscode-peacock
      - karigari.chat
      - KnisterPeter.vscode-commitizen
      - KnisterPeter.vscode-jira
      - kubernetes-tools.k8s
      - lkytal.FlatUI
      - logerfo.gitlab-notifications
      - marcostazi.VS-code-vagrantfile
      - mauve.terraform
      - mhutchie.git-graph
      - monokai.theme-monokai-pro-vscode
      - ms-azuretools.vscode-docker
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - ms-python.python
      - ms-vscode-remote.remote-containers
      - ms-vscode-remote.remote-ssh
      - ms-vscode-remote.remote-ssh-edit
      - ms-vscode-remote.remote-ssh-explorer
      - ms-vscode-remote.remote-wsl
      - ms-vscode-remote.vscode-remote-extensionpack
      - ms-vscode.Go
      - ms-vscode.powershell
      - ms-vscode.vscode-typescript-tslint-plugin
      - ms-vsliveshare.vsliveshare
      - ms-vsliveshare.vsliveshare-audio
      - ms-vsliveshare.vsliveshare-pack
      - msjsdiag.debugger-for-chrome
      - neverik.go-critic
      - owenfarrell.vscode-vault
      - p1c2u.docker-compose
      - PKief.material-icon-theme
      - redhat.vscode-yaml
      - rrivera.vscode-gitlab-explorer
      - rupisaini.vscode-ansible-linter
      - shd101wyy.markdown-preview-enhanced
      - sidneys1.gitconfig
      - SolarLiner.linux-themes
      - sozercan.slack
      - tht13.python
      - timonwong.ansible-autocomplete
      - TqrHsn.vscode-docker-registry-explorer
      - vector-of-bool.gitflow
      - vitorsalgado.vscode-glide
      - vscode-icons-team.vscode-icons
      - vscoss.vscode-ansible
      - waderyan.gitblame
      - WakaTime.vscode-wakatime
      - yuchiu2002.default-material-dark-theme
      - Zim.vsc-docker
    # Extensions to be uninstalled if not already absent
    visual_studio_code_extensions_absent:
      - # extension 3


gsetting:
  - key: org.gnome.nautilus.preferences.default-folder-viewer
    value: "'list-view'"
  - key: org.gnome.shell.remember-mount-password
    value: "true"
  - key: org.gnome.nautilus.preferences.always-use-location-entry
    value: "true"
  - key: org.gnome.nautilus.list-view.use-tree-view
    value: "true"    
  - key: org.gnome.mutter.wayland.xwayland-allow-grabs
    value: "true"   
